version: "3.8"

services: 
  database:
    image: mcr.microsoft.com/mssql/server:latest
    container_name: rentxcore_db
    ports: 
      - 14333:1433
    environment: 
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Rdf123!@#
  app:
    build: .
    container_name: rentxcore_api
    ports: 
      - 3333:3333
    volumes: 
      - .:/App
    depends_on: 
      - database